import { Roboto } from 'next/font/google'
import "./globals.css";
import Navbar from '@/components/shared/Navbar';


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
export const metadata = {
  title: "Abc website",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html className='container mx-auto' lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
